# NOTE(pierre): this gitlab ci file works with host docker networks because the
# gitlab runner has the docker.sock mounted inside. Thats also the reason we
# dont need to use docker dind(docker in docker).
# see docker socket binding:
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

# stages in the order we are going through them
stages:
  - deploy

image: tmaier/docker-compose:20.10

deploy:
  stage: deploy

  # determines the gitlab runner that will be run. specific to my gitlab
  # instance.
  tags:
    - anything

  rules:
    # runs job if on main branch
    - if: $CI_COMMIT_BRANCH == "main"

  script:
    - cp ./docker-compose-prod.yaml ./docker-compose.yaml
    - docker-compose build --no-cache
    - echo "Spinning up containers..."
    - docker-compose up -d
